#!/bin/bash

cat /sys/kernel/ece453_digidiplo/ready
echo writing to datasize
echo 0 > /sys/kernel/ece453_digidiplo/datasize
echo writing to data
echo 0x00000000 > /sys/kernel/ece453_digidiplo/data
echo writing to shift
echo 1 > /sys/kernel/ece453_digidiplo/shift
echo writing to display
echo 1 > /sys/kernel/ece453_digidiplo/display
echo 0x00000000 > /sys/kernel/ece453_digidiplo/data
#cc=0
# while [ $cc -lt 300 ]; do
	count=0
	while [ $count -lt 306 ]; do
		echo 1 > /sys/kernel/ece453_digidiplo/shift
		echo 1 > /sys/kernel/ece453_digidiplo/display
		let count=count+1
	done
#echo 0x80000000 > /sys/kernel/ece453_digidiplo/data
#echo next one
#let cc=cc+1
#done

echo done with loop
	

